---

type: image
dataset: EMNIST
test_batch_size: 1000
lr: 0.1
momentum: 0.9
decay: 0.0005
batch_size: 64
mu: 1.0

no_models: 20
epochs: 50
retrain_no_times: 1
milestones: [2, 4, 6]
norm_bound: 100
dp_sigmma: 0.01
number_of_total_participants: 20
sampling_dirichlet: true
dirichlet_alpha: 0.5
eta: 1.0

p: 2
beta: 150

save_model: false
save_on_epochs: [10, 100, 500, 1000, 2000, 5000]
#resumed_model: false
#resumed_model: recover/model_cifar_10k.pt.tar
#resumed_model: model_image_Aug.20_10.38.31/model_last.pt.tar.epoch

resumed_model:
environment_name: ppdl_experiment

# pixel pattern Backdoor(true)
modify_poison: true

# Semantic Backdoor(Semantic Characteristic)
poison_type: wall

# manually chosen images for tests
poison_images_test: [330, 568, 3934, 12336, 30560]
poison_images: [30696, 33105, 33615, 33907, 36848, 40713, 41706]

# target label
poison_label_swap: 7
size_of_secret_dataset: 100
poisoning_per_batch: 7
poison_test_repeat: 1000
is_poison: true
random_compromise: false
noise_level: 0.01

# trigger
poison_patterns: [[0, 0], [0, 1], [0, 2], [0, 3],
                  [0, 6], [0, 7], [0, 8], [0, 9],
                  [3, 0], [3, 1], [3, 2], [3, 3],
                  [3, 6], [3, 7], [3, 8], [3, 9]]

retrain_poison: 1
scale_weights: 1.0
poison_lr: 0.1
poison_momentum: 0.9
poison_decay: 0.005
poison_step_lr: true
clamp_value: 1.0
alpha_loss: 1.0
number_of_adversaries: 4
poisoned_number: 10
results_json: true

# simple tunning flag
ST_flag: false
ST_lr: 0.005
ST_retrain_times: 4